DreamsTrips/urls.py
import django.views.static
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from DreamsTrips.views import home_view, mission_view, \
    DreamWorkersListView, send_contact_message, send_quote_request, \
    policy_view, GalleryListView, ViewGallery
from trips import urls as trips_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # Project apps
    url(r'^$', home_view, name='home'),
    url(r'^mission/$', mission_view, name='mission'),
    url(r'^policies/$', policy_view, name='politicas'),
    url(r'^team/$', DreamWorkersListView.as_view(), name='team'),
    url(r'^gallery/$', GalleryListView.as_view(), name='gallery'),
    url(r'^detail_gallery/(?P<gallery_pk>\d+)/$', ViewGallery.as_view(), name='single_trip_gallery'),
    url(r'^trips/', include(trips_urls)),
    # url(r'^profile/', include('profiles.urls')),
    url(r'^send_contact_message/', send_contact_message, name="send_contact_message"),
    url(r'^send_cotization_request/', send_quote_request, name="send_cotiztion_request"),

    url(r'^static/(?P<path>.*)$', django.views.static.serve,
        {'document_root': settings.STATIC_ROOT}),
    url(r'^media/(?P<path>.*)$', django.views.static.serve,
        {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
]

trips/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from trips.views import TripsListView, ViewTrip

__author__ = 'rafael'

urlpatterns = [

    url(r'^trip/(?P<trip_pk>\d+)/$', ViewTrip.as_view(),
        name='single_trip'),
    url(r'^list_trips/', TripsListView.as_view(), name="trips"),

]

rbac/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class Role(models.Model):
    role = models.CharField(
        max_length=45,
        verbose_name='Rol'
    )

    def __str__(self):
        return self.role


@python_2_unicode_compatible
class Operation(models.Model):
    operation = models.CharField(
        max_length=45,
        verbose_name='Operación'
    )

    def __str__(self):
        return self.operation


class Object(models.Model):
    obj = models.CharField(
        max_length=45,
        verbose_name='Objeto'
    )

    def __str__(self):
        return self.obj


@python_2_unicode_compatible
class UserRole(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE,
        verbose_name='Usuario'
    )

    role = models.ForeignKey(
        Role, on_delete=models.CASCADE,
        verbose_name='Rol'
    )

    status = models.BooleanField(
        default=True,
        verbose_name='Estado'
    )

    def __str__(self):
        return '%s es %s' % (
            self.user.username,
            self.role
        )


@python_2_unicode_compatible
class PermissonAssignment(models.Model):
    role = models.ForeignKey(
        Role, on_delete=models.CASCADE,
        verbose_name='Rol'
    )

    operation = models.ForeignKey(
        Operation, on_delete=models.CASCADE,
        verbose_name='Operación'
    )

    obj = models.ForeignKey(
        Object, on_delete=models.CASCADE,
        verbose_name='Objeto'
    )

    def __str__(self):
        return '%s puede %s %s' % (
            self.role,
            self.operation,
            self.obj
        )

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="{% static 'bs3/css/bootstrap.min.css' %}" rel="stylesheet"/>

    <link href="{% static 'css/materialize.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/custom.css' %}" rel="stylesheet"/>
    <link href="{% static 'font-awesome/css/font-awesome.css' %}"
          rel="stylesheet"/>
    {% block css %}
    {% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<nav>
    <div class="row">
        <div class="col-md-12">
            <div class="col-md-4">
                {#            <img src="{% static 'images/dreams_logo.png' %}" style="width:30%;">#}
            </div>
            <div class="col-md-8">
                <div class="col-md-12" align="center">
                    {#                   <a class="waves-effect waves-light btn" style="bottom: 0; position: absolute;">Viaja ahora</a>#}
                    {#                   &nbsp;#}
                    <a href="{% url "trips" %}"><img
                            src="{% static 'images/btn_travel_now.png' %}"
                            style="width:30%;"></a>
                </div>
                <div class="col-md-12 col-sm-12"
                     style="font-family:Beyond-The-Mountains; font-size:18px;">
                    <div class="col-md-2 col-sm-2"><a href="{% url 'home' %}"
                                                      style="color:black; ">
                        <img src="{% static 'images/btn_home.png' %}" style="">
                        Inicio</a></div>
                    <div class="col-md-3 col-sm-3"><a href="{% url 'team' %}"
                                                      style="color:black;">
                        <img src="{% static 'images/btn_team.png' %}" style="">
                        Con&oacute;cenos</a></div>
                    <div class="col-md-4 col-sm-4">
                        <a href="{% url 'gallery' %}" style="color:black;">
                            <img src="{% static 'images/btn_gallery.png' %}"
                             style=""> Galer&iacute;a de Im&aacute;genes</a>
                    </div>
                    <div class="col-md-3 col-sm-3">
                        <a href="#contactModal" style="color:black;"><img
                                src="{% static 'images/btn_contact.png' %}">
                            Cont&aacute;ctanos</a></div>
                </div>
            </div>
        </div>

    </div>

</nav>
<body>

<div id="contactModal" class="modal" style="box-shadow: none;">
    <div class="modal-content" style="font-family:Beyond-The-Mountains;">
        <h4>Contactanos</h4>

        <form id="contactForm" action="{% url 'send_contact_message' %}" method="post">
            {% csrf_token %}
            <input id="first_name" type="text" class="validate" name="first_name">
            <label for="first_name">Nombre</label>

            <input id="last_name" type="text" class="validate" name="last_name">
            <label for="last_name">Apellidos</label>

            <input id="phone" type="text" class="validate" name="phone">
            <label for="phone">Tel&eacute;efono</label>

            <input id="email" type="email" class="validate" name="email">
            <label for="email">E-mail</label>

            <textarea id="comment" class="materialize-textarea" name="comment"></textarea>
            <label for="comment">Comentarios</label>
            </textarea>

        </form>
         <button class="btn waves-effect waves-light" id="send_message">Enviar
         </button>

    </div>
</div>

<div id="cotizModal" class="modal" style="box-shadow: none;">
    <div class="modal-content" style="font-family:Beyond-The-Mountains;">
        <h4>Pide tu cotizaci&oacute;n</h4>

        <form id="cotizationRequest">
            <input id="first_name" type="text" class="validate" name="first_name">
            <label for="first_name">Nombre</label>
            <input id="last_name" type="text" class="validate" name="last_name">
            <label for="last_name">Apellidos</label>
            <input id="email" type="email" class="validate" name="email">
            <label for="email">E-mail</label>
            <input id="phone" type="text" class="validate" name="phone">
            <label for="phone">Tel&eacute;fono</label>

          <textarea
                  placeholder="Cuentanos sobre tu viaje perfecto y nosotros te contactaremos para hacerlo realidad."
                  id="comment" class="materialize-textarea"></textarea>
            <label for="comment"></label>

        </form>
        <button class="btn waves-effect waves-light" id="send_cotization_request">Enviar
         </button>
    </div>
</div>
{% block content %}

{% endblock %}
</body>
<footer class="page-footer">
    <div class="container">
        <div class="row">
            <div class="col l12 s12" align="center">
                <a class="btn-floating btn-large waves-effect waves-light dream-blue facebook-rounded margin-10"
                   href="https://www.facebook.com/DREAMSTRIPS02/"
                   target="_blank">
                    <i class="fa fa-facebook" aria-hidden="true"></i>
                </a>
                <a class="btn-floating btn-large waves-effect waves-light dream-blue margin-10"
                   href="{% url 'team' %}" target="_blank">
                    <i class="fa fa-whatsapp" aria-hidden="true"></i>
                </a>
                <a class="btn-floating btn-large waves-effect waves-light dream-blue margin-10"
                   href="http://instagram.com/dreamstrips"
                   target="_blank">
                    <i class="fa fa-instagram" aria-hidden="true"></i>
                </a>
                <a class="btn-floating btn-large waves-effect waves-light dream-blue margin-10"
                   href="https://twitter.com/Dreams_Trips" target="_blank">
                    <i class="fa fa-twitter" aria-hidden="true"></i>
                </a>
                </a>
                <a class="btn-floating btn-large waves-effect waves-light dream-blue margin-10"
                   href="https://youtu.be/thCp9RKYgj4" target="_blank">
                    <i class="fa fa-youtube-play" aria-hidden="true"></i>
                </a>
            </div>
            <div class="col l12 s12" align="center">
               <a href="{% url 'mission' %}">Dreams Trips</a>  | <a href="{% url 'politicas' %}">Trips Policy</a>
            </div>
        </div>
    </div>

</footer>

<script src="{% static 'jQuery/jQuery-2.1.4.min.js' %}"></script>
<script src="{% static 'bs3/js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/materialize.js' %}"></script>
<script>
        $(document).ready(function () {
            // the "href" attribute of .modal-trigger must specify the modal ID that wants to be triggered
            $('.modal').modal();

            $(".facebook-rounded").on('click', function () {
                console.log("FACEBOOK");
                window.open("https://www.facebook.com/sharer/sharer.php?u={{ request.path }}", '_blank')
            });
            $(".twitter-rounded").on('click', function () {
                window.open("https://twitter.com/home?status={{ request.path }}", '_blank')
            });
            $(".google-rounded").on('click', function () {
                window.open("https://plus.google.com/share?url={{ request.path }}", '_blank')
            });


            $("#send_message").on('click', function () {
                var data = new FormData($('#contactForm').get(0));

                var send_message_url = "{% url 'send_contact_message' %}";
                $.ajax({
                    url: send_message_url,
                    type: "post",
                    data: data,
                    processData: false,
                    contentType: false,
                    success: function (data) {
                        Materialize.toast('Mensaje Enviado!', 4000)
                    },
                    error: function (data) {
                        console.log('ERROR', data);
                        Materialize.toast('Tu mensaje no pudo ser enviado. Inténtalo de nuevomás tarde', 4000)
                    }
                });
            });

            $("#send_cotization_request").on('click', function () {
                var data = new FormData($('#cotizationRequest').get(0));
                var send_message_url = "{% url 'send_contact_message' %}";
                $.ajax({
                    url: send_message_url,
                    type: "post",
                    data: data,
                    processData: false,
                    contentType: false,
                    success: function (data) {
                        Materialize.toast('Mensaje Enviado!', 4000)
                    },
                    error: function (data) {
                        console.log('ERROR', data);
                        Materialize.toast('Tu mensaje no pudo ser enviado. ' +
                                'Inténtalo de nuevo más tarde', 4000)
                    }
                });
            });

        });
    </script>
{% block js %}

{% endblock %}

</html>

templates/gallery.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
    <div class="container" style="width:100%; padding-left:0; padding-right:0;">
    <div class="carousel" style="background-color: #4AB9B2;" align="center">
        {% for image in object_list %}
            <a class="carousel-item"  href="{% url 'single_trip_gallery' gallery_pk=image.pk %}">
            {% if image.main_photo %}
                <img src="{{ image.main_photo.url }}" style="height:100%; width:auto;">
            {% endif %}
            </a>
        {% endfor %}
    </div>
    </div>
{% endblock %}

{% block js %}
<script>
$(document).ready(function(){
     $('.carousel').carousel();
});
</script>
{% endblock %}

templates/group_trip_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
    <div class="container"
         style="width:100%; padding-left:0; margin-left:0; padding-right:0; margin-right:0; ">

        <div class="row">
            <div class="col l12 s12">
                <div class="col l12 s12"
                     style="background-color: #4AB9B2; color:white; ">
                    <div class="col l5 s12 xs12" style="margin-top:25px;" align="center">
                        <img src="{{ trip.circle_photograph.url }}"
                             style="width:500px; height:auto; margin-bottom:15px;">
                    </div>
                    <div class="col l7 s12 xs12" style="margin-top:25px;">
                        <div class="col l12 s12">
                            <p align="justify">{{ trip.description|safe }}</p>

                            <p>{% for item in itinerary_items %}
                                {{ item.description }}<br>
                            {% endfor %}
                            </p>
                        </div>
                    <div class="col l12 s12">
                        <a href="{% url 'team' %}">
                            <img src="{% static 'images/botones_boton_reserva.png' %}" align="right" style="width:27%;">
                        </a>
                    {% if trip.itinerary_file %}
                        <a href="{{ trip.itinerary_file.url }}" target="_blank">
                            <img src="{% static 'images/botones_boton_itininerio.png' %}" align="left" style="width:30%;">
                        </a>
                        {% else %}
                        <a>
                            <img src="{% static 'images/botones_boton_itininerio.png' %}" align="left" style="width:30%;">
                        </a>
                    {% endif %}
                    </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/group_trip_selector.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
    <div class="container"
         style="width:100%; padding-left:0;  padding-right:0; background-color: #4AB9B2;"
            >

    <div class="carousel" align="center">
        {% for trip in object_list %}
            <a class="carousel-item" href="{% url 'single_trip' trip_pk=trip.pk %}">
                {% if trip.photograph %}
                <img src="{{ trip.photograph.url }}" style="height:100%; width:auto;">
                {% endif %}
            </a>
        {% endfor %}
    </div>

    </div>
{% endblock %}

{% block js %}
<script>
$(document).ready(function(){
     $('.carousel').carousel({padding: 400});
});
</script>
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
<div style="background-color: #4AB9B2; background-size:100%, auto; min-height:500px " >
<div class="row" align="center">
    <div class="col l12">
        <div class="col l4 s12" align="center">
            <a href="{% url "trips" %}" style="width:10%;">
{#                <img src="{% static 'images/btn_group_trips.png' %}" style="width:95%;">#}
                <img src="{% static 'images/viajes_grupales_icon.png' %}" style="width:200px; margin-top:140px"
                    onmouseover="this.src='{% static 'images/viajes_grupales_text.png' %}'"
                    onmouseout="this.src='{% static 'images/viajes_grupales_icon.png' %}'"
                border="0" alt=""/>
            </a>
        </div>
         <div class="col l4 s12" align="center" >
            <img src="{% static 'images/dreams_logo_white.png' %}" style="width:400px;">
        </div>
        <div class="col l4 s12" align="center">
            <a href="#cotizModal" style="width:100px; ">
{#                <img src="{% static 'images/btn_private_trips.png' %}" style="width:95%;">#}
                <img src="{% static 'images/viajes_privados_icon.png' %}" style="width:200px; margin-top:140px"
                    onmouseover="this.src='{% static 'images/viajes_privados_text.png' %}'"
                    onmouseout="this.src='{% static 'images/viajes_privados_icon.png' %}'"
                border="0" alt=""/>
            </a>
        </div>
    </div>
</div>
</div>
{% endblock %}

templates/mission.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
    <div class="container" style="width:100%; padding-left:0; margin-left:0">

    <div class="row">
    <div class="col l12 s12">
        <div class="col l8 s8" style="background-color: #51d1ce; color:white; min-height:415px;">
            <div class="col l12 s12" style="margin-top:25px;">
                <p align="justify">DREAMS TRIPS es una empresa turística dedicada a la
                    intermediación, organización y realización de proyectos,
                    planes e itinerarios, además, de la elaboración y venta de
                productos turísticos (Hospedajes, vuelos, etc.) a sus clientes
                y determinados proveedores de viajes.</p>
            </div>

        <div class="col l12 s12" style="margin-top:25px;">
            <div class="col l6 s6">
                MISIÓN
                <p align="justify">Brindar el mejor servicio superando las expectativas de
                nuestros dreamers con el fin de lograr una plena satisfacción
                mediante productos turísticos a precios competitivos que les
                permitan realizar viajes para un desarrollo placentero.</p>
            </div>
            <div class="col l6 s6">
                VISIÓN
                <p align="justify">Ser una cadena de agencias de viajes virtuales confiables y
                seguras, que ofrezcan tranquilidad yun excelene servicio a
                nuestros dreamers en viajes dentro y fuera del país.</p>
            </div>
        </div></div>

        <div class="col l4 s4" align="center">

            <img src="{% static 'images/dreams_logo.png' %}" style="margin-top: 20px;">

            <a href="{% url 'team' %}"><img src="{% static 'images/conoce_button.png' %}" style="margin-top: 20px;"></a>
        </div>
    </div>
    </div>
    </div>
{% endblock %}

templates/single_trip_gallery.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
    <div class="container" style="width:100%; padding-left:0; padding-right:0;">
    <div class="carousel" style="background-color: #4AB9B2;" align="center">
        {% for image in object_list %}
            <a class="carousel-item">
            {% if image.photograph %}
                <img src="{{ image.photograph.url }}" style="height:100%; width:auto;">
            {% endif %}
            </a>
        {% endfor %}
    </div>
    </div>
{% endblock %}

{% block js %}
<script>
$(document).ready(function(){
     $('.carousel').carousel();
});
</script>
{% endblock %}

templates/team.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
    <div class="container"
         style="width:100%; padding-left:0; padding-right:0;">
    <div class="carousel" style="background-color: #4AB9B2;" align="center">
        {% for member in object_list %}
            {% if member.facebook_link %}
                <a class="carousel-item" href="{{ member.facebook_link }}" target="_blank">
            {% else %}
                <a class="carousel-item">
            {% endif %}
            {% if member.profile_pic %}
                <img src="{{ member.profile_pic.url }}" style="height:auto; width:100%; border-radius:50%">
                <span style="color:black">
                    {{ member.auth_user.first_name }} {{ member.auth_user.last_name }}
                    <br>
                    <i class="fa fa-whatsapp" aria-hidden="true"></i> {{ member.phone }}
                </span>
                {% else %}
                <span style="color:black">
                    {{ member.auth_user.first_name }} {{ member.auth_user.last_name }}
                    <br>
                    <i class="fa fa-whatsapp" aria-hidden="true"></i> {{ member.phone }}
                </span>
            {% endif %}
            </a>
        {% endfor %}
    </div>
    </div>

{% endblock %}

{% block js %}
<script>
$(document).ready(function(){
     $('.carousel').carousel();
});
</script>
{% endblock %}

templates/trips_policy.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
    <div class="container" style="width:100%; padding-left:0; margin-left:0">

        <div class="row">
            <div class="col l12 s12">
                <div class="col l8 s8"
                     style="background-color: #51d1ce; color:white; min-height:415px;">
                    <div class="col l12 s12" style="margin-top:25px;">
                        <p align="justify"><b>Políticas de Reservación en Grupo (No aplica planes
                            todo incluído):</b><br>
                            • Todas las reservaciones son vía deposito o
                            transferencia bancaria.<br>
                            • El seguro de viajero cubre únicamente dentro de la
                            unidad de transporte.<br>
                            • Cinco días antes de realizar el viaje, éste deberá
                            estar liquidado al cien porciento; si el viaje es
                            liquidado después de esta fecha se cobrará una multa
                            del diez porciento por impuntualidad del
                            pago.<br>
                            • Dreams Trips no se hace responsable por las personas
                            que no lleguen en tiempo y forma a la
                            salida del viaje, ya sea en el inicio de éste o en
                            los traslados del mismo.<br>
                            • 15 días antes del viaje no puede haber cancelaciones
                            de ningún lugar reservado, de ser así el
                            cliente deberá liquidar la totalidad del boleto
                            rescindido. (Puede existir variación, verificar el
                            itinerario correspondiente al viaje).<br>
                            • Bajo ninguna circunstancia hay reembolsos por parte
                            de la Agencia, a menos que ésta cancelé
                            el viaje, siendo así el reembolso es 100% íntegro.<br>
                            • En la operación del viaje se manejan tiempos
                            estimados, hay factores externos que pueden
                            modificarlos (clima, peajes, tráfico, etc).<br>
                            • El coordinador tiene la facultad de realizar cambios
                            en el itinerario de acuerdo a las condiciones
                            de operación del viaje que puedan poner en riesgo la
                            integridad y seguridad del grupo
                            • Es responsabilidad del coordinador comunicar los
                            cambios existentes en la operación del viaje.<br>
                            Al momento de realizar la reservación el cliente da
                            por confirmado el conocimiento total de las
                            políticas.</p>

                        <p align="justify"><b>Políticas de Reservación en grupo en planes todo
                            incluido:</b><br>
                            • Todas las reservaciones son vía deposito o
                            transferencia bancaria.<br>
                            • El seguro de viajero cubre únicamente dentro de la
                            unidad de transporte.<br>
                            • 30 días antes de realizar el viaje, éste deberá
                            estar liquidado al cien porciento; si el viaje es
                            liquidado después de esta fecha se cobrará una multa
                            del 15% por impuntualidad del pago.<br>
                            • Dreams Trips no se hace responsable por las
                            personas que no lleguen en tiempo y forma a la
                            •salida del viaje, ya sea en el inicio de éste o en
                            los traslados del mismo.<br>
                            • 60 días antes del viaje no puede haber cancelaciones
                            de ningún lugar reservado, de ser así el
                            cliente deberá liquidar la totalidad del boleto
                            rescindido.<br>
                            • Bajo ninguna circunstancia hay reembolsos por parte
                            de la Agencia, a menos que ésta cancelé
                            el viaje, siendo así el reembolso es 100% íntegro.<br>
                            • En la operación del viaje se manejan tiempos
                            estimados, hay factores externos que pueden
                            modificarlos (clima, peajes, tráfico, etc).<br>
                            • El coordinador tiene la facultad de realizar cambios
                            en el itinerario de acuerdo a las condiciones
                            de operación del viaje que puedan poner en riesgo la
                            integridad y seguridad del grupo
                            Es responsabilidad del coordinador comunicar los
                            cambios existentes en la operación del viaje.<br>
                            • Al momento de realizar la reservación el cliente da
                            por confirmado el conocimiento total de las
                            políticas.</p>
                    </div>
                </div>

                <div class="col l4 s4" align="center">
                    <img src="{% static 'images/dreams_logo.png' %}"
                         style="margin-top: 20px;">

                    <a href="{% url 'team' %}"><img
                            src="{% static 'images/conoce_button.png' %}"
                            style="margin-top: 20px;"></a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}